---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - testee.elp-max.com
  resources:
  - testees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testee.elp-max.com
  resources:
  - testees/finalizers
  verbs:
  - update
- apiGroups:
  - testee.elp-max.com
  resources:
  - testees/status
  verbs:
  - get
  - patch
  - update
