apiVersion: super.elp-max.com/v1
kind: Superpod
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: superpod-sample
spec:
  # TODO(user): Add fields here
