apiVersion: testee.elp-max.com/v1
kind: Testee
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: testee-sample
spec:
  # TODO(user): Add fields here
